/// Flutter icons Fitness
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fitness
///      fonts:
///       - asset: fonts/Fitness.ttf
///
/// 
/// * Maki, Copyright (C) Mapbox, LCC
///         Author:    Mapbox
///         License:   BSD (https://github.com/mapbox/maki/blob/gh-pages/LICENSE.txt)
///         Homepage:  http://mapbox.com/maki/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class Fitness {
  Fitness._();

  static const _kFontFam = 'Fitness';
  static const _kFontPkg = null;

  static const IconData swimming = IconData(0xe838, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData basketball_ball = IconData(0xf434, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
